USE [master]
GO

/****** Object:  Database [ProjectA]    Script Date: 2/23/2023 4:10:46 PM ******/
CREATE DATABASE [ProjectA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ProjectA', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\ProjectA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ProjectA_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\ProjectA_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProjectA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ProjectA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ProjectA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ProjectA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ProjectA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ProjectA] SET ARITHABORT OFF 
GO

ALTER DATABASE [ProjectA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ProjectA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ProjectA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ProjectA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ProjectA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ProjectA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ProjectA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ProjectA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ProjectA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ProjectA] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ProjectA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ProjectA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ProjectA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ProjectA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ProjectA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ProjectA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ProjectA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ProjectA] SET RECOVERY FULL 
GO

ALTER DATABASE [ProjectA] SET  MULTI_USER 
GO

ALTER DATABASE [ProjectA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ProjectA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ProjectA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ProjectA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ProjectA] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ProjectA] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ProjectA] SET QUERY_STORE = ON
GO

ALTER DATABASE [ProjectA] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [ProjectA] SET  READ_WRITE 
GO

